# Aggregate data continuity checks. No source specimen remapping is inferred automatically.
suppressPackageStartupMessages({library(dplyr); library(readr); library(tidyr); library(lubridate); library(glue)})
source("utils/clif_io.R")
start <- safe_ts(config_value(config, "study_start_date", env = "STUDY_START_DATE", default = NA_character_))
end <- safe_ts(config_value(config, "study_end_date", env = "STUDY_END_DATE", default = NA_character_)) + days(1)
micro <- read_tbl("microbiology_culture") %>% transmute(collect_dttm = safe_ts(collect_dttm), fluid_name = clean_micro_label(fluid_name), fluid_category = coalesce(clean_micro_label(fluid_category), "missing"), method_category = clean_micro_label(method_category)) %>% filter(method_category == "culture", !is.na(collect_dttm)) %>% filter(is.na(start) | collect_dttm >= start, is.na(end) | collect_dttm < end) %>% mutate(calendar_month = floor_date(collect_dttm, "month"))
if (!nrow(micro)) stop("No culture rows for continuity QC.")
last_month <- max(micro$calendar_month)
monthly <- micro %>% count(calendar_month, fluid_category, name = "n_source_rows")
continuity <- monthly %>% group_by(fluid_category) %>% summarise(first_observed_month = min(calendar_month), last_observed_month = max(calendar_month), n_months_observed = n(), n_source_rows = sum(n_source_rows), .groups = "drop") %>% mutate(months_absent_at_end = round(as.numeric(difftime(last_month, last_observed_month, units = "days")) / 30.4375), discontinuity_flag = n_months_observed >= 12 & months_absent_at_end >= 3, site_name = clif_site_name)
name_mapping <- micro %>% count(fluid_name, fluid_category, calendar_month, name = "n_source_rows") %>% group_by(fluid_name) %>% mutate(n_categories_for_name = n_distinct(fluid_category)) %>% ungroup() %>% filter(n_categories_for_name > 1) %>% mutate(site_name = clif_site_name)
data <- read_culture_data(start, end)
stay_qc <- tibble(site_name = clif_site_name, n_icu_stays = nrow(data$icu_admissions), n_stays_with_imputed_out = sum(data$icu_admissions$icu_interval_missing_out), fraction_stays_with_imputed_out = mean(data$icu_admissions$icu_interval_missing_out), n_unique_culture_events = n_distinct(data$events$culture_event_id), n_indeterminate_events = sum(data$events$result_status == "Indeterminate"), n_mixed_events = sum(data$events$result_status == "Mixed/contaminated"))
out <- project_output_dir("quality_checks");stamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
write_csv(continuity, file.path(out, glue("specimen_category_continuity_{clif_site_name}_{stamp}.csv")))
write_csv(name_mapping, file.path(out, glue("specimen_name_mapping_changes_{clif_site_name}_{stamp}.csv")))
write_csv(stay_qc, file.path(out, glue("cohort_quality_checks_{clif_site_name}_{stamp}.csv")))
write_csv(mutate(monthly, site_name = clif_site_name), file.path(out, glue("monthly_source_specimen_categories_{clif_site_name}_{stamp}.csv")))
if (any(continuity$discontinuity_flag)) warning("Specimen categories disappear before the end of observation. Review quality_checks and source ETL; use verified specimen_category_overrides.csv rules or restrict the study window before interpreting specimen trends.")
