# Synthetic end-to-end ASE stage, including both groups, AST, plots, and export audit.
suppressPackageStartupMessages({library(dplyr);library(tidyr);library(lubridate);library(readr);library(jsonlite)})
source("tests/test_ase.R")
source("tests/test_ase_characteristics.R")
scratch<-Sys.getenv("ASE_TEST_OUTPUT",tempfile("clif_ase_integration_"));if(dir.exists(scratch))stop("Use a new ASE_TEST_OUTPUT directory")
dir.create(scratch,recursive=TRUE);tables<-file.path(scratch,"tables");dir.create(tables)
dir.create(file.path(scratch,"config","mcide"),recursive=TRUE);dir.create(file.path(scratch,"utils"))
file.copy("utils/ase",file.path(scratch,"utils"),recursive=TRUE)
file.copy(list.files("config/mcide",full.names=TRUE),file.path(scratch,"config","mcide"))
file.copy("config/specimen_category_overrides.csv",file.path(scratch,"config"))
expanded<-lapply(raw,function(x)bind_rows(lapply(0:23,function(i){
 for(col in intersect(c("hospitalization_id","patient_id"),names(x)))x[[col]]<-paste0(x[[col]],"_",i)
 for(col in names(x)[grepl("_dttm$",names(x))])x[[col]]<-x[[col]] %m+% months(i)
 x
})))
x<-expanded$microbiology_culture %>% mutate(patient_id=hospitalization_id,organism_id=paste0("o_",hospitalization_id),order_dttm=collect_dttm,result_dttm=collect_dttm+days(1),fluid_name="blood",method_name="culture",organism_name="escherichia coli",organism_category="escherichia_coli",organism_group="escherichia")
expanded$microbiology_culture<-x
expanded$respiratory_support<-expanded$hospitalization %>% transmute(hospitalization_id,recorded_dttm=admission_dttm,device_category="room_air")
for(n in names(expanded))write_csv(expanded[[n]],file.path(tables,paste0("clif_",n,".csv")))
ast<-x %>% crossing(antimicrobial_category=c("ceftriaxone","meropenem")) %>% transmute(organism_id,antimicrobial_category,susceptibility_category=if_else((as.integer(sub(".*_","",hospitalization_id))+as.integer(sub("_.*","",hospitalization_id)))%%3==0,"non_susceptible","susceptible"))
write_csv(ast,file.path(tables,"clif_microbiology_susceptibility.csv"))
config_path<-file.path(scratch,"config.json");write_json(list(site_name="ASE_SYNTHETIC",repo=scratch,tables_path=tables,file_type="csv"),config_path,auto_unbox=TRUE)
old<-Sys.getenv(c("CLIF_CONFIG_PATH","CLIF_REPO","CLIF_RUN_ID"),unset=NA_character_)
Sys.setenv(CLIF_CONFIG_PATH=config_path,CLIF_REPO=scratch,CLIF_RUN_ID="ase_integration")
log<-file.path(scratch,"ase_stage.log")
status<-system2(file.path(R.home("bin"),"Rscript"),"code/11_ase_stratified_analysis.R",stdout=log,stderr=log)
if(status!=0){cat(tail(readLines(log),40),sep="\n");stop("ASE integration failed: ",log)}
run<-file.path(scratch,"output","runs","ase_integration")
get_csv<-function(pattern)read_csv(list.files(file.path(run,"ase"),pattern=pattern,full.names=TRUE)[1],show_col_types=FALSE)
stopifnot(get_csv("^ase_availability")$analysis_status=="completed")
qc<-get_csv("^ase_classification_qc");stopifnot(qc$n[qc$metric=="ase_hospitalizations"]==72,qc$n[qc$metric=="non_ase_hospitalizations"]==144,qc$n[qc$metric=="excluded_or_unclassifiable_hospitalizations"]==24)
cohort<-get_csv("^ase_cohort_summary");stopifnot(sum(cohort$n_hospitalizations)==216)
table1<-get_csv("^ase_characteristics_table1");stopifnot(all(c("display_ASE","display_Non-ASE") %in% names(table1)))
characteristics<-get_csv("^ase_characteristics_long");stopifnot(all(characteristics$n_hospitalizations[characteristics$ase_group=="ASE"]==72),all(characteristics$n_hospitalizations[characteristics$ase_group=="Non-ASE"]==144))
stopifnot(filter(characteristics,characteristic=="in_hospital_death",ase_group=="ASE",level=="yes")$n==24)
stopifnot(filter(characteristics,characteristic=="recorded_vasopressor",ase_group=="ASE",level=="yes")$n==48)
monthly<-get_csv("^ase_monthly_culture_rates");stopifnot(sum(monthly$n_culture_events)==192,all(c("ASE","Non-ASE") %in% monthly$ase_group))
stopifnot(get_csv("^ase_susceptibility_availability")$analysis_status=="completed")
models<-get_csv("^ase_organism_temporal_models");stopifnot(all(c("ASE","Non-ASE") %in% models$ase_group))
ast_models<-get_csv("^ase_susceptibility_temporal_models");stopifnot(all(c("susceptible_detection_rate","non_susceptible_detection_rate","non_susceptible_fraction") %in% ast_models$outcome))
status<-system2(file.path(R.home("bin"),"Rscript"),"code/07_prepare_site_exports.R",stdout=log,stderr=log);stopifnot(status==0)
audit<-read_csv(list.files(file.path(run,"site_exports"),pattern="privacy_audit",full.names=TRUE),show_col_types=FALSE);stopifnot(nrow(audit)==0)
stopifnot(length(list.files(file.path(run,"ase"),pattern="png$"))>=10)
# Missing required ASE data skips explicitly; it never fabricates a non-ASE cohort.
file.rename(file.path(tables,"clif_labs.csv"),file.path(tables,"labs_unavailable.csv"))
Sys.setenv(CLIF_RUN_ID="missing_ase_inputs")
status<-system2(file.path(R.home("bin"),"Rscript"),"code/11_ase_stratified_analysis.R",stdout=log,stderr=log);stopifnot(status==0)
missing<-read_csv(list.files(file.path(scratch,"output","runs","missing_ase_inputs","ase"),pattern="availability",full.names=TRUE),show_col_types=FALSE);stopifnot(missing$analysis_status=="skipped_required_tables_unavailable")
for(n in names(old))if(is.na(old[[n]]))Sys.unsetenv(n) else do.call(Sys.setenv,setNames(list(old[[n]]),n))
cat("ASE integration passed; artifacts: ",run,"\n",sep="")
