# Full synthetic site run with the standard AST schema; writes only to a temporary project.
suppressPackageStartupMessages({library(dplyr);library(tidyr);library(readr);library(lubridate);library(jsonlite)})
repo <- normalizePath(getwd()); scratch <- Sys.getenv("BUDDY_TEST_OUTPUT",tempfile("clif_culture_integration_"));if(dir.exists(scratch))stop("Use a fresh BUDDY_TEST_OUTPUT directory.");dir.create(scratch,recursive=TRUE)
tables <- file.path(scratch,"tables");dir.create(tables)
dir.create(file.path(scratch,"config","mcide"),recursive=TRUE)
file.copy(list.files("config/mcide",full.names=TRUE),file.path(scratch,"config","mcide"))
file.copy("config/specimen_category_overrides.csv",file.path(scratch,"config"))
f <- crossing(month_index=0:35,j=0:11) %>% mutate(patient_id=paste0("p",month_index,"_",j),hospitalization_id=paste0("h",month_index,"_",j), admission_dttm=as.POSIXct(sprintf("%d-%02d-%02d",2018+month_index%/%12,month_index%%12+1,j+2),tz="UTC"),discharge_dttm=admission_dttm+days(3),organism_id=paste0("o",month_index,"_",j),organism_category=c("staphylococcus_aureus","escherichia_coli","pseudomonas_aeruginosa","candida_albicans")[j%%4+1],organism_category=if_else(j==10,"no_growth",if_else(j==11,NA_character_,organism_category)),fluid_name=if_else(j==0,"bal",if_else(j%%2==0,"blood","sputum")),fluid_category=if_else(j==0,if_else(month_index<20,"respiratory_tract_lower","other_unspecified"),if_else(j%%2==0,"blood_buffy","respiratory_tract")))
write_csv(f %>% select(patient_id,hospitalization_id,admission_dttm,discharge_dttm) %>% mutate(age_at_admission=55),file.path(tables,"clif_hospitalization.csv"))
adt <- bind_rows(f %>% transmute(hospitalization_id,in_dttm=admission_dttm,out_dttm=admission_dttm+days(2),location_category="icu"), f %>% transmute(hospitalization_id,in_dttm=admission_dttm+days(1),out_dttm=discharge_dttm,location_category="icu"))
write_csv(adt,file.path(tables,"clif_adt.csv"))
write_csv(f %>% transmute(patient_id,hospitalization_id,organism_id,order_dttm=admission_dttm,collect_dttm=admission_dttm+hours(3),result_dttm=admission_dttm+days(1),fluid_name,fluid_category,method_name="culture",method_category="culture",organism_name=gsub("_"," ",organism_category),organism_category,organism_group=if_else(is.na(organism_category),NA_character_,sub("_.*","",organism_category))), file.path(tables,"clif_microbiology_culture.csv"))
ast <- f %>% filter(j<10) %>% crossing(antimicrobial_category=c("ceftriaxone","meropenem")) %>% transmute(organism_id,antimicrobial_name=antimicrobial_category,antimicrobial_category,sensitivity_name="MIC",susceptibility_name=if_else((j+month_index%/%12)%%5<2,"resistant","susceptible"),susceptibility_category=if_else((j+month_index%/%12)%%5<2,"non_susceptible","susceptible"))
write_csv(ast,file.path(tables,"clif_microbiology_susceptibility.csv"))
config_path <- file.path(scratch,"config.json")
write_json(list(site_name="SYNTHETIC",repo=scratch,tables_path=tables,file_type="csv"),config_path,auto_unbox=TRUE)
old <- Sys.getenv(c("CLIF_CONFIG_PATH","CLIF_REPO","CLIF_RUN_ID","CLIF_TABLES_PATH"),unset=NA_character_)
Sys.setenv(CLIF_CONFIG_PATH=config_path,CLIF_REPO=scratch);Sys.unsetenv(c("CLIF_RUN_ID","CLIF_TABLES_PATH"))
log <- file.path(scratch,"pipeline.log")
status <- system2(file.path(R.home("bin"),"Rscript"),c("code/00_run_pipeline.R"),stdout=log,stderr=log)
if(status!=0) {cat(tail(readLines(log),40),sep="\n");stop("Synthetic pipeline failed: ",log)}
run <- list.dirs(file.path(scratch,"output","runs"),recursive=FALSE)
stopifnot(length(run)==1)
preflight<-read_csv(file.path(run,"provenance","preflight_source_availability.csv"),show_col_types=FALSE)
stopifnot(nrow(preflight)==3,all(preflight$n_source_rows_in_study_window>0))
source("utils/study_settings.R")
manifest<-jsonlite::fromJSON(file.path(run,"provenance","run_manifest.json"))
stopifnot(manifest$study_start_date==study_settings$study_start_date,manifest$study_end_date==study_settings$study_end_date)
get_csv <- function(folder,pattern) read_csv(list.files(file.path(run,folder),pattern=pattern,full.names=TRUE)[1],show_col_types=FALSE)
cohort <- get_csv("cohort","cohort_summary")
stopifnot(cohort$n_culture_events==432,cohort$n_positive_culture_events==360)
rates <- get_csv("rates","monthly_admission_cohort")
stopifnot(sum(rates$n_icu_admissions)==432,all(rates$proportion_icu_admissions_cultured==1))
qc <- get_csv("quality_checks","specimen_category_continuity")
stopifnot(any(qc$discontinuity_flag))
models <- get_csv("susceptibility","temporal_models")
stopifnot(any(models$model_status=="estimated"),all(c("susceptible_detection_rate","non_susceptible_detection_rate","non_susceptible_fraction") %in% models$outcome))
audit <- get_csv("site_exports","privacy_audit")
stopifnot(nrow(audit)==0)
stopifnot(get_csv("susceptibility","availability")$analysis_status=="completed")
stopifnot(length(list.files(file.path(run,"susceptibility"),pattern="susceptibility_testing_coverage.*png$"))==1)
stopifnot(length(list.files(file.path(run,"susceptibility"),pattern="^(susceptible_detection_rate|non_susceptible_detection_rate|non_susceptible_fraction).*png$"))==3)
x<-get_csv("susceptibility","monthly_organism_antimicrobial")
stopifnot(all(c("observation_status","linkage_fraction","testing_fraction_linkable","rate_model_eligible","fraction_model_eligible") %in% names(x)))
# Missing optional table must skip instead of inferring susceptible status.
file.rename(file.path(tables,"clif_microbiology_susceptibility.csv"),file.path(tables,"ast_unavailable.csv"))
Sys.setenv(CLIF_RUN_ID=basename(run))
status <- system2(file.path(R.home("bin"),"Rscript"),"code/09_susceptibility_trends.R",stdout=log,stderr=log)
stopifnot(status==0)
available <- list.files(file.path(run,"susceptibility"),pattern="availability",full.names=TRUE)
a <- read_csv(available[which.max(file.info(available)$mtime)],show_col_types=FALSE)
stopifnot(!a$susceptibility_table_available,a$analysis_status=="skipped_table_unavailable")
# A site with observed cultures but no positives is a valid complete practices run.
file.rename(file.path(tables,"ast_unavailable.csv"),file.path(tables,"clif_microbiology_susceptibility.csv"))
micro_path<-file.path(tables,"clif_microbiology_culture.csv")
negative<-read_csv(micro_path,show_col_types=FALSE) %>% mutate(organism_name="no growth",organism_category="no_growth",organism_group="no_growth")
write_csv(negative,micro_path)
Sys.unsetenv("CLIF_RUN_ID")
negative_log<-file.path(scratch,"negative_pipeline.log")
status<-system2(file.path(R.home("bin"),"Rscript"),"code/00_run_pipeline.R",stdout=negative_log,stderr=negative_log)
if(status!=0){cat(tail(readLines(negative_log),40),sep="\n");stop("All-negative pipeline failed.")}
negative_run<-setdiff(list.dirs(file.path(scratch,"output","runs"),recursive=FALSE),run)
stopifnot(length(negative_run)==1,jsonlite::fromJSON(file.path(negative_run,"provenance","run_manifest.json"))$analysis_status=="completed")
negative_ast<-read_csv(list.files(file.path(negative_run,"susceptibility"),pattern="availability",full.names=TRUE)[1],show_col_types=FALSE)
stopifnot(negative_ast$analysis_status=="no_linkable_icu_isolates")
Sys.setenv(CLIF_RUN_ID=basename(run))
# The audit must reject the new private culture-event identifiers.
write_csv(tibble(culture_event_id=1),file.path(run,"injected_private_event.csv"))
status <- system2(file.path(R.home("bin"),"Rscript"),"code/07_prepare_site_exports.R",stdout=log,stderr=log)
stopifnot(status!=0)
for (name in names(old)) if (is.na(old[[name]])) Sys.unsetenv(name) else do.call(Sys.setenv,setNames(list(old[[name]]),name))
cat("Synthetic pipeline, optional-table skip, and export rejection passed. Artifacts: ",scratch,"\n",sep="")
