suppressPackageStartupMessages(library(testthat))
config_path<-tempfile(fileext=".json")
jsonlite::write_json(list(site_name="MINIMAL",repo=tempdir(),tables_path=tempdir(),file_type="csv"),config_path,auto_unbox=TRUE)
old<-Sys.getenv("CLIF_CONFIG_PATH",unset=NA_character_)
Sys.setenv(CLIF_CONFIG_PATH=config_path)
source("utils/config.R")
test_that("minimal site config uses project-wide study settings", {
 expect_equal(sort(names(config)),sort(c("site_name","repo","tables_path","file_type")))
 expect_setequal(names(study_settings),c("study_start_date","study_end_date"))
 expect_false(anyNA(as.Date(unlist(study_settings))))
 expect_lte(as.Date(study_settings$study_start_date),as.Date(study_settings$study_end_date))
 template<-jsonlite::fromJSON("config/config_template.json")
 expect_setequal(names(template),names(config))
})
if(is.na(old))Sys.unsetenv("CLIF_CONFIG_PATH") else Sys.setenv(CLIF_CONFIG_PATH=old)
